---
## handlers for ivansible.vagrant.share

- name: activate systemd mounts
  ansible.builtin.systemd:
    name: remote-fs.target
    state: restarted
    daemon_reload: true
  become: true
  ## possible error: "path is already a mount point, refusing start"
  # failed_when: false
...
