---
dependencies: []

galaxy_info:
  author: "Ivan Andreev"
  description: "configure vagrant guest"
  company: "IvanSible"
  license: MIT
  min_ansible_version: 2.8

  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic

  galaxy_tags:
    - vagrant
    - virtualbox
    - guest
...
