---
namespace: ivansible
name: vagrant
version: 1.0.0

description: Ansible collection for Vagrant machines

authors:
  - Ivan Andreev <ivandeex@gmail.com>

tags:
  - linux
  - vagrant
  - virtualbox
  - cifs
  - ipv6
  - dns
  - cloudflare
  - vultr

# https://python-semanticversion.readthedocs.io/en/latest/#requirement-specification
# namespace.name: version_range
dependencies: {}

repository: https://github.com/ivansible/vagrant
documentation: https://github.com/ivansible/vagrant
homepage: https://github.com/ivansible/vagrant
issues: https://github.com/ivansible/vagrant/issues

readme: README.md
license: MIT

build_ignore:
  - '*.pyc'
  - '*.tar'
...
