---
dependencies: []

galaxy_info:
  author: "Ivan Andreev"
  description: "Fix SSH port, username, python interpreter"
  company: "IvanSible"
  license: MIT
  min_ansible_version: 2.5

  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic

  galaxy_tags:
    - linux
    - ssh
...
