---
#===================
# 1. scan inventory

- name: read inventory settings
  set_fact:
    orig_host: "{{ ansible_host | default(ansible_ssh_host) }}"
    orig_user: "{{ ansible_user | default(ansible_ssh_user) | default('') }}"
    orig_port: "{{ ansible_port | default(ansible_ssh_port) | default('') }}"
    orig_pass: "{{ ansible_password | default('') }}"
    orig_keyfile: "{{ ansible_private_key_file | default('') }}"
    orig_python: "{{ ansible_python_interpreter
                   | default(linen_default_python) }}"
    linen_keyfile_: "{{ (linen_keyfile != 'default')
                      | ternary(linen_keyfile, linen_default_keyfile) }}"
    linen_new_keyfile_: "{{ (linen_new_keyfile != 'default')
                          | ternary(linen_new_keyfile, linen_default_keyfile) }}"
  tags: linen_settings

# when debugging, you can set these manually
- name: reset found facts
  set_fact:
    found_user: "-"
    found_port: "-"
    found_python: "-"
    found_pass: ""
    found_keyfile: ""


#=============================
# 2. investigate connectivity

- name: disable hostkey checking
  set_fact:
    ansible_ssh_host_key_checking: false

- name: investigate connection problems
  block:
    - name: check for problems with ssh port and username
      wait_for_connection:
        timeout: "{{ linen_wait_timeout }}"

    - name: check for problems with python interpreter
      ping:
  rescue:
    - name: detect the best connection method
      import_tasks: detect.yml
      # when debugging, you can set these manually
      when: found_user == '-' or found_port == '-' or found_python == '-'

    - debug:
        msg:
          - "Detected settings:"
          - "- port: {{ found_port | default('-',true) }}"
          - "- user: {{ found_user | default('-',true) }}"
          - "- pass: {{ found_pass | default('-',true) }}"
          - "- keyfile: {{ found_keyfile | default('-',true) }}"
          - "- python: {{ found_python | default('-',true) }}"
    - name: please see detected settings...
      pause:
        seconds: "{{ linen_pause_timeout }}"

    - name: initialize ansible ssh user
      set_fact:
        ansible_ssh_user: "{{ found_user }}"
      when: found_user not in ['','-',orig_user]
    - name: initialize ansible ssh port
      set_fact:
        ansible_ssh_port: "{{ found_port }}"
      when: found_port not in ['','-',orig_port]
    - name: initialize ansible ssh pass
      set_fact:
        ansible_ssh_pass: "{{ found_pass }}"
      when: found_pass not in ['','-',orig_pass]
    - name: initialize ansible ssh private key
      set_fact:
        ansible_ssh_private_key_file: "{{ found_keyfile }}"
      when: found_keyfile not in ['','-',orig_keyfile]
    - name: initialize ansible python interpreter
      set_fact:
        ansible_python_interpreter: "{{ found_python }}"
      when: found_python not in ['','-',orig_python]

    - name: ping to verify new connection
      ping:
  tags: linen_detect


#=========================
# 3. adjust host settings

- name: gather facts once connected
  setup:

- name: disable pipelining before going root
  set_fact:
    ansible_ssh_pipelining: false

- name: adjust host settings
  import_tasks: tune.yml
  become: yes
  tags: linen_tune


#=========================
# 4. print inventory info

- block:
    - name: clear facts
      meta: clear_facts

    - name: gather facts as new user
      setup:

    - name: the last ping
      ping:

    - debug:
        msg:
          - "Inventory entry for your new host:"
          - "{{ (orig_host | regex_search('^[0-9]')
                | ternary('newhost' + orig_host | regex_search('\\.[0-9]+$')
                                                | regex_replace('\\.', '-'),
                          orig_host))
              + ' ansible_host=' + orig_host
              + ((new_port | default(22) == 22)
                | ternary('', ' ansible_port=' + new_port | string))
              + ((new_user | default('') == '')
                | ternary('', ' ansible_user=' + new_user))
              + ((new_keyfile | default('') in ['', '-'])
                | ternary('', ' ansible_private_key_file=' + new_keyfile))
              + ((new_python | default('') in ['', linen_default_python])
                | ternary('', ' ansible_python_interpreter=' + new_keyfile))
             }}"
  tags: linen_info
...
