---
- name: check whether virtualbox guest additions are installed
  ansible.builtin.stat:
    path: /sbin/rcvboxadd
  register: vbguest_tools

- name: check whether guest additions kernel modules are up-to-date
  ansible.builtin.stat:
    path: "{{ vag_vbguest_module_path }}"
  register: vbguest_kernel_module

- name: setup virtualbox guest additions
  block:
    - name: temporarily unhold kernel packages
      ## this step runs with block only when kernel modules are absent
      # noqa no-changed-when
      ansible.builtin.command:
        cmd: apt-mark unhold {{ packages }}
      vars:
        packages: "{{ vag_vbguest_kernel_packages |join(' ') }}"

    - name: install prerequisites for virtualbox guest additions
      ansible.builtin.apt:
        name:
          - linux-headers-generic
          - linux-headers-{{ ansible_kernel }}
          - build-essential

    - name: rebuild kernel modules for virtualbox guest additions
      # noqa no-changed-when
      ansible.builtin.command: /sbin/rcvboxadd quicksetup all

    - name: restart guest additions services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: restarted
        enabled: true
      loop:
        - vboxadd
        - vboxadd-service
  become: true
  when:
    - vag_vbguest_enable |bool
    - vbguest_tools.stat.exists
    - not vbguest_kernel_module.stat.exists

- name: freeze kernel version to prevent problems with guest additions
  when: vag_vbguest_freeze_kernel |bool
  ansible.builtin.command:
    cmd: apt-mark hold {{ packages }}
  vars:
    packages: "{{ vag_vbguest_kernel_packages |join(' ') }}"
  become: true
  changed_when: false
...
