---
## ====================
## = 1. scan inventory

- name: read inventory settings
  ansible.builtin.set_fact:
    orig_host: "{{ ansible_host |d(ansible_ssh_host) }}"
    orig_user: "{{ ansible_user |d(ansible_ssh_user) |d('') }}"
    orig_port: "{{ ansible_port |d(ansible_ssh_port) |d('') }}"
    orig_pass: "{{ ansible_password |d('') }}"
    orig_keyfile: "{{ ansible_private_key_file |d('') }}"
    orig_python: "{{ ansible_python_interpreter
                   | d(linen_default_python) }}"
    linen_keyfile_: "{{ (linen_keyfile != 'default')
                      | ternary(linen_keyfile, linen_default_keyfile) }}"
    linen_new_keyfile_: "{{ (linen_new_keyfile != 'default')
                          | ternary(linen_new_keyfile, linen_default_keyfile) }}"
  tags: linen_settings

## when debugging, you can set these manually
- name: reset found facts
  ansible.builtin.set_fact:
    found_user: '-'
    found_port: '-'
    found_python: '-'
    found_pass: ''
    found_keyfile: ''


## ==============================
## = 2. investigate connectivity

- name: disable hostkey checking
  ansible.builtin.set_fact:
    ansible_ssh_host_key_checking: false

- name: investigate connection problems
  block:
    - name: check for problems with ssh port and username, warning (even error) is ok
      ansible.builtin.wait_for_connection:
        timeout: "{{ linen_wait_timeout }}"

    - name: check for problems with python interpreter (will be rescued if it fails)
      ansible.builtin.ping:
  rescue:
    - name: detect the best connection method
      ansible.builtin.import_tasks: detect.yml
      ## when debugging, you can set these manually
      when: found_user == '-'
            or found_port == '-'
            or found_python == '-'

    - name: print detected settings
      ansible.builtin.debug:
        msg:
          - "******** ATTENTION! ********"
          - "Detected settings:"
          - "- port: {{ found_port |d('-',true) }}"
          - "- user: {{ found_user |d('-',true) }}"
          - "- pass: {{ found_pass |d('-',true) }}"
          - "- keyfile: {{ found_keyfile |d('-',true) }}"
          - "- python: {{ found_python |d('-',true) }}"
    - name: please see detected settings...
      ansible.builtin.pause:
        seconds: "{{ linen_pause_timeout }}"

    - name: initialize ansible ssh user
      ansible.builtin.set_fact:
        ansible_ssh_user: "{{ found_user }}"
      when: found_user not in ['','-',orig_user]
    - name: initialize ansible ssh port
      ansible.builtin.set_fact:
        ansible_ssh_port: "{{ found_port }}"
      when: found_port not in ['','-',orig_port]
    - name: initialize ansible ssh pass
      ansible.builtin.set_fact:
        ansible_ssh_pass: "{{ found_pass }}"
      when: found_pass not in ['','-',orig_pass]
    - name: initialize ansible ssh private key
      ansible.builtin.set_fact:
        ansible_ssh_private_key_file: "{{ found_keyfile }}"
      when: found_keyfile not in ['','-',orig_keyfile]
    - name: initialize ansible python interpreter
      ansible.builtin.set_fact:
        ansible_python_interpreter: "{{ found_python }}"
      when: found_python not in ['','-',orig_python]

    - name: ping to verify new connection
      ansible.builtin.ping:
  tags: linen_detect


## ==========================
## = 3. adjust host settings

- name: gather facts once connected
  ansible.builtin.setup:

- name: disable pipelining before going root
  ansible.builtin.set_fact:
    ansible_ssh_pipelining: false

- name: adjust host settings
  ansible.builtin.import_tasks: tune.yml
  become: true
  tags: linen_tune


## ==========================
## = 4. print inventory info

- block:
    - name: clear facts
      ansible.builtin.meta: clear_facts

    - name: gather facts as new user
      ansible.builtin.setup:

    - name: the last ping
      ansible.builtin.ping:

    - name: print new inventory host
      ansible.builtin.debug:
        msg:
          - "******** SUCCESS! ********"
          - "Inventory entry for your new host:"
          - "{{ (orig_host | regex_search('^[0-9]')
                | ternary('newhost' + orig_host | regex_search('\\.[0-9]+$')
                                                | regex_replace('\\.', '_'),
                          orig_host))
              + ' ansible_host=' + orig_host
              + ((new_port |d(22) == 22)
                | ternary('', ' ansible_port=' + new_port | string))
              + ((new_user |d('') in [''])
                | ternary('', ' ansible_user=' + new_user))
              + ((new_keyfile |d('') in ['', '-'])
                | ternary('', ' ansible_private_key_file=' + new_keyfile))
              + ((new_python |d('') in ['', linen_default_python])
                | ternary('', ' ansible_python_interpreter=' + new_python))
             }}"
  tags: linen_info
...
