---
- name: check that ufw is present
  stat:
    path: /usr/sbin/ufw
    get_checksum: false
  register: ufw_binary
  tags: linen_firewall

- name: install ufw
  block:
    - name: apt install ufw without update (fast)
      apt:
        name: ufw
  rescue:
    - name: apt install ufw with update (slower)
      apt:
        name: ufw
        update_cache: true
      register: apt_ufw_result
      until: apt_ufw_result is successful
      retries: 5
  when: linen_ufw |bool and not ufw_binary.stat.exists
  tags: linen_firewall

- name: allow new port through ubuntu firewall in advance
  ufw:
    rule: allow
    port: "{{ new_port }}"
    proto: tcp
  when: linen_ufw |bool and linen_secure |bool
  tags: linen_firewall

- name: configure new ssh port
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^Port"
    line: "Port {{ new_port }}"
  register: ssh_config

- name: restart ssh
  systemd:
    name: ssh
    state: restarted
  when: ssh_config is changed

- name: switch connection to new port
  set_fact:
    ansible_ssh_port: "{{ new_port }}"

- name: reset ansible connection
  meta: reset_connection

- name: reconnect after switching ports
  block:
    - name: wait for reconnection
      wait_for_connection:
        timeout: "{{ linen_wait_timeout }}"
      register: result
      until: result is successful
      retries: "{{ linen_conn_retries }}"
  when: ssh_config is changed

- name: enable ubuntu firewall
  ufw:
    state: enabled
  when: linen_ufw |bool and linen_secure |bool
  tags: linen_firewall

- name: pause before testing connection
  wait_for:
    timeout: "{{ linen_wait_timeout }}"
  when: ssh_config is changed
  tags: linen_firewall

- name: test connection with new port
  ping:
  register: ping_result
  until: ping_result is successful
  when: ssh_config is changed
  tags: linen_firewall

- name: warn about open ssh port
  debug:
    msg:
      - "******** WARNING! ********"
      - "Old SSH port {{ found_port }} is left open!"
  when: linen_secure |bool
        and ssh_config is changed
  tags: linen_firewall
...
