---
dependencies: []

galaxy_info:
  role_name: vag_share
  author: "Ivan Andreev"
  description: "Create a CIFS mount of temporary developer directory from vagrant host."
  company: "IvanSible"
  license: MIT
  min_ansible_version: 2.5

  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic

  galaxy_tags:
    - developer
    - vagrant
    - samba
    - cifs
...
