---
# handlers for vag-share

- name: activate systemd mounts
  systemd:
    name: remote-fs.target
    state: restarted
    daemon_reload: true
  become: true
  ## possible error: "path is already a mount point, refusing start"
  # ignore_errors: true
...
