---
# defaults for vag-share

is_permitted: false

vag_share_host: 192.168.1.1
vag_share_name: ""
vag_share_user: "{{ ansible_user_id }}"
vag_share_pass: secret_pass
vag_share_mount: "{{ ansible_user_dir }}/shares/host"

vag_share_uid: "{{ ansible_user_uid }}"
vag_share_gid: "{{ ansible_user_gid }}"

vag_share_depend_on: network-online.target
vag_share_install_on: multi-user.target

vag_share_cred_file: "{{ ansible_user_dir }}/.vag-share-credentials"
...
